<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="MySQL - exception_deal@localhost" uuid="83a89822-4575-4eb2-b372-4b7dc7eef392">
      <driver-ref>mysql</driver-ref>
      <synchronize>true</synchronize>
      <configured-by-url>true</configured-by-url>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://localhost:3306/exception_deal</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="nacos@localhost" uuid="120817a5-56fb-4c28-ae1c-b3ca230a56ac">
      <driver-ref>mysql</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://localhost:3306/nacos</jdbc-url>
    </data-source>
    <data-source source="LOCAL" name="exception_deal@localhost" uuid="51500e7f-0dc1-4649-aa5e-2b562fd05b30">
      <driver-ref>mysql</driver-ref>
      <synchronize>true</synchronize>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://localhost:3306/exception_deal</jdbc-url>
    </data-source>
  </component>
</project>